# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'HelloTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloTest

  # Elegant HTTP Networking in Swift
  # https://github.com/Alamofire/Alamofire
  # Swift 4.2
  pod 'Alamofire', '~> 4.8.0'

  target 'HelloTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
